name: Static Site CI
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Build Upptime site
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./site/status-page/__sapper__/export
          cname: status.bugagent.com
          force_orphan: true
